[IV-21-22] Objetivo 2
Xileon310/IV-Project pull request #22
Opened 2021-11-10 09:32 UTC by albertotc99

Este PR contiene la justificación de la elección de Go como lenguaje de programación y la creación de las clases necesarias para representar una entidad Actividad y conseguir así el [[M1]](https://github.com/Xileon310/IV-Project/milestone/1). 

Se han creado las clases Zona, Usuario y Actividad. Se cierran los issues #19, #20 y  #21.

2021-11-10 12:05 UTC, Xileon310 commented
Lo veo listo para revisión @JJ

2021-11-11 08:44 UTC, albertotc99 commented
He borrado todo lo relacionado con los usuarios, dejando solo lo relacionado con las actividades.

2021-11-11 19:32 UTC, JJ requested changes
El código no se desarrolla con respecto a un issue, y de hecho no hay ningún issue que desarrolle HUs en el código. De esa forma no se puede avanzar, y es imposible saber si los atributos de struct que se usa son los correctos.

2021-11-16 13:06 UTC, albertotc99 commented
Ya he realizado los cambios pertinentes. Espero la aprobación de @Xileon310.
Se han intentado seguir las convenciones que propone [Godoc](https://go.dev/blog/godoc) en la documentación del código.

2021-11-19 06:32 UTC, JJ requested changes
Deben revisarse la lista de comprobación del objetivo 2. Ningún issue sigue el formato que tiene que seguir, ni el desarrollo parece tener ningún tipo de dirección más allá de darle nombres a los campos vagamente relacionados con el objeto del desarrollo.

2021-11-19 06:32 UTC, JJ commented on pkg/actividad/actividad.go
> +	zona Zona
El código se define en un solo commit, y no justifica los diferentes atributos. Los mensajes de commit no siguen las buenas prácticas. El issue #19 tampoco describe qué problema plantea, y ni siquiera se siguen los consejos en el comentario como es "Añadir un campo descripción" (que no sé si servirá a la lógica de negocio). En general, es imposible con ese issue saber qué es lo que hay que hacer y por qué.

2021-11-19 06:32 UTC, JJ commented on pkg/actividad/actividad.go
> +	return a
¿No será mejor hacerlo en una sola línea?

2021-11-19 06:32 UTC, JJ commented on pkg/actividad/zona.go
> +	codigo_postal int32
Igual que el anterior. ¿Para qué sirve a la lógica de negocio saber el país? ¿Qué formato van a seguir todos ellos?

2021-11-19 12:15 UTC, albertotc99 commented on pkg/actividad/actividad.go
> +	zona Zona
> El código se define en un solo commit, y no justifica los diferentes atributos. 
¿Es necesario definir una clase como esta, que es bastante sencilla, en varios commits? La justificación de los atributos la he incluido en el issue para no tener que modificar los mensajes de commit. 

> Los mensajes de commit no siguen las buenas prácticas.
Utilizaré las buenas prácticas en los siguientes.

 > El issue #19 tampoco describe qué problema plantea, y ni siquiera se siguen los consejos en el comentario como es "Añadir un campo descripción" (que no sé si servirá a la lógica de negocio). En general, es imposible con ese issue saber qué es lo que hay que hacer y por qué.
Faltaba por borrar del milestone el campo descripción, pero ya se decidió que no era necesario para la lógica de negocio. Ya está indicado en la conversación del issue.

2021-11-19 12:25 UTC, albertotc99 commented on pkg/actividad/actividad.go
> +	return a
Cierto 👍🏼

2021-11-19 13:15 UTC, albertotc99 commented
He modificado los issues, aunque tampoco estoy seguro de si " sigue el formato que tiene que seguir". Sé que deben ser la descripción de un problema que tengo que resolver como programador y creo que lo son. Quedo a la espera de feedback.
He seguido las buenas prácticas para los commits de https://www.theserverside.com/video/Follow-these-git-commit-message-guidelines, y he modificado el código incluyendo los cambios sugeridos.
Espero la aprobación o las indicaciones de @Xileon310

2021-11-19 13:50 UTC, Xileon310 commented
@JJ Estaría listo para revisión.

2021-11-21 08:33 UTC, JJ requested changes
Aparte de lo comentado en el #19 , no hace falta poner dos veces el issue en el mensaje de commit, sino que el mensaje de commit no repita lo que es evidente que hace (modificar no sé qué) sino que diga de qué forma resuelva el problema.

2021-11-21 08:33 UTC, JJ commented on pkg/actividad/zona.go
> +	codigo_postal string
El código postal implica la localidad y la provincia. De hecho, tiene más precisión. Pero una vez más no sé qué va a hacer con el código postal la lógica de negocio.

2021-11-24 13:24 UTC, albertotc99 commented
En esta nueva versión se han hecho los siguientes cambios:
* Se ha eliminado el código postal que no era necesario para la lógica de negocio. Se han mantenido el resto de atributos de la zona porque se consideran necesarios para identificar de forma unívoca el lugar donde se realiza la actividad.
* Se ha añadido un enumerado que indica la categoría a la que pertenece una actividad ya que se considera necesario para la lógica de negocio (#23).

2021-11-24 13:28 UTC, Xileon310 commented
Lo veo todo perfecto, diría que está listo para revisión @JJ

2021-11-26 06:16 UTC, JJ approved these changes
Sigo pensando que la `Zona` no sirve para resolver el problema. Si es para hacer senderismo o escalada, ¿no habrá que poner dónde se empieza por coordenadas? Pero eso le queda ya a @Xileon310 para resolver en el objetivo siguiente, por parte de @albertotc99 está el objetivo logrado.

2021-11-26 07:30 UTC, merged